export const siteConfig = {
  name: "مطعم واستراحة ابن النبك",
  shortName: "ابن النبك",
  slogan: "وجهتكم المتكاملة في النبك",
  description:
    "مطعم، كافيه وتراس، صالة أفراح، حلويات، وألعاب أطفال في مكان واحد",
  address: "أوتستراد دمشق، مقابل مدخل مدينة النبك",
  heroImage: "/images/hero.jpg",

  logoSrc: "/branding/logo.png",
  logoAlt: "شعار مطعم واستراحة ابن النبك",

  // ===== بيانات مؤقتة - يتم تحديثها لاحقاً =====
  phoneDisplay: "+963 000 000 000",
  phoneHref: "tel:+963000000000",
  whatsappNumber: "963000000000",
mapsHref: "https://maps.app.goo.gl/ReDofToXDJXsmmVx6",
mapsEmbed:
  "https://www.google.com/maps?q=34.0286,36.7236&hl=ar&z=17&output=embed",
  // ===== السوشال ميديا (اختياري) =====
  social: {
    facebook: "",
    instagram: "",
    tiktok: "",
  },
};

export const whatsappMessage = encodeURIComponent(
  "مرحبًا، أرغب بالطلب أو الاستفسار من مطعم واستراحة ابن النبك"
);

export const whatsappHref = `https://wa.me/${siteConfig.whatsappNumber}?text=${whatsappMessage}`;

export const navLinks = [
  { label: "الرئيسية", href: "#top" },
  { label: "أقسامنا", href: "#sections" },
  { label: "المعرض", href: "#gallery" },
  { label: "المنيو", href: "/menu" },
  { label: "صالة الأفراح", href: "#events" },
  { label: "تواصل معنا", href: "#contact" },
];

export const stats = [
  { value: "3", label: "طوابق رئيسية" },
  { value: "عائلي", label: "مناسب للعائلات" },
  { value: "صيفي", label: "تراس خارجي موسمي" },
];

export const venueSections = [
  {
    title: "الطابق الأول",
    subtitle: "المطعم + الحلويات + ألعاب الأطفال",
    description:
      "يضم قسم المطعم الرئيسي، وقسمًا خاصًا بالحلويات، بالإضافة إلى مساحة مخصصة لألعاب الأطفال لتجربة عائلية متكاملة.",
    items: ["قسم المطعم", "قسم الحلويات", "ألعاب الأطفال"],
  },
  {
    title: "الطابق الثاني",
    subtitle: "الكافيه + التراس",
    description:
      "جلسات مريحة وأجواء راقية تناسب اللقاءات العائلية والجلسات المسائية، مع مساحة تراس مميزة.",
    items: ["قسم الكافيه", "التراس", "جلسات مريحة"],
  },
  {
    title: "الطابق الثالث",
    subtitle: "صالة الأفراح",
    description:
      "صالة مخصصة لاستقبال المناسبات الخاصة والأفراح في أجواء أنيقة وخدمة مميزة.",
    items: ["صالة أفراح", "مناسبات خاصة", "استفسار عبر الهاتف"],
  },
  {
    title: "المساحة الخارجية",
    subtitle: "تراس صيفي أمام الاستراحة",
    description:
      "في فصل الصيف، تتوفر جلسات خارجية مميزة أمام الاستراحة لتجربة أكثر انتعاشًا وراحة.",
    items: ["تراس خارجي", "جلسات صيفية", "واجهة مريحة"],
  },
];

export const highlights = [
  {
    title: "قسم الحلويات",
    text: "ركن خاص للحلويات يضيف لمسة ضيافة راقية ويكمل تجربة الزوار بنكهات مميزة.",
  },
  {
    title: "ألعاب الأطفال",
    text: "مساحة مخصصة للأطفال تمنح العائلة راحة أكبر أثناء الجلسة داخل المطعم والاستراحة.",
  },
  {
    title: "الكافيه والتراس",
    text: "جلسات هادئة وتصميم مريح يناسب اللقاءات اليومية والجلسات المسائية مع الأصدقاء والعائلة.",
  },
  {
    title: "صالة الأفراح",
    text: "خيار مثالي للمناسبات الخاصة ضمن مكان واحد يجمع بين الضيافة والأجواء الأنيقة.",
  },
];

// ===== العملات المتاحة =====
export const currencies = [
  { code: "SYP", label: "ل.س", name: "ليرة سورية" },
  { code: "USD", label: "$", name: "دولار" },
  { code: "TRY", label: "₺", name: "ليرة تركية" },
];

// ===== أقسام المنيو =====
export const menuCategories = [
  {
    id: "breakfast",
    title: "الإفطار",
    icon: "🍳",
    items: [
      {
        name: "صحن زيتون",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "صحن لبنة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "30,000", USD: "", TRY: "" },
      },
      {
        name: "صحن جبنة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "30,000", USD: "", TRY: "" },
      },
      {
        name: "صحن خضرة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "20,000", USD: "", TRY: "" },
      },
      {
        name: "حمّص باللحمة",
        desc: "100 غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "فول بالزيت",
        desc: "للشخص الواحد",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
        {
        name: "فول بلبن",
        desc: "للشخص الواحد",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "حمّص بالزيت",
        desc: "للشخص الواحد",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "حمّص باللبن",
        desc: "للشخص الواحد",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25000", USD: "", TRY: "" },
      },
      {
        name: "فتة بالزيت",
        desc: "للشخص الواحد",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "فتة بالسمنة",
        desc: "للشخص الواحد",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
      {
        name: "زعتر ابن النبك",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "7,000", USD: "", TRY: "" },
      },
      {
        name: "زعتر و قشوان",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "7,000", USD: "", TRY: "" },
      },
      {
        name: "بيضة مقلية",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "4,000", USD: "", TRY: "" },
      },
       {
        name: "خبز تميس",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "10,000", USD: "", TRY: "" },
      },
      {
        name: "خبز تميس بالجبنة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "خبز تميس دبل جبنة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
      {
        name: "صحن قشطة عربية",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "appetizers",
    title: "المقبلات",
    icon: "🥗",
    items: [
      {
        name: "حمص باللحمة",
        desc: "100 g",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "حمص باللحمة",
        desc: "200 g",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "120,000", USD: "", TRY: "" },
      },
      {
        name: "مسبحة باللية",
        desc: "100 g",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "65,000", USD: "", TRY: "" },
      },
      {
        name: "صحن مقبلات مشكل",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "95,000", USD: "", TRY: "" },
      },
      {
        name: "مسبحة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "متبل",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "بابا غنوج",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "حمص بيروتي",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "متبل شوندر",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "محمرة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "شنكليش",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "30,000", USD: "", TRY: "" },
      },
      {
        name: "كبة نية",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "90,000", USD: "", TRY: "" },
      },
      {
        name: "هبرة نية",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "90,000", USD: "", TRY: "" },
      },
      {
        name: "جاط خضرة اكسترا",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "250,000", USD: "", TRY: "" },
      },
      {
        name: "بطاطا مقلية",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "برك جبنة",
        desc: "القطعة الواحدة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "7,000", USD: "", TRY: "" },
      },
      {
        name: "زبدية لبن",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "5,000", USD: "", TRY: "" },
      },
      {
        name: "صحن مايونيز",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "10,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "salads",
    title: "السلطات",
    icon: "🥬",
    items: [
      {
        name: "تبولة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
      {
        name: "فتّوش",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "سلطة شرقيّة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
      {
        name: "سلطة أرمينية",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
      {
        name: "سلطة سيزر",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "65,000", USD: "", TRY: "" },
      },
      {
        name: "سلطة سويسرية",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "سلطة جرجير",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
      {
        name: "سلطة شوندر",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "eastern",
    title: "المأكولات الشرقية",
    icon: "🍛",
    items: [
      {
        name: "فريكة لحمة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "120,000", USD: "", TRY: "" },
      },
      {
        name: "فريكة دجاج",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "60,000", USD: "", TRY: "" },
      },
      {
        name: "كبسة لحمة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "120,000", USD: "", TRY: "" },
      },
      {
        name: "كبسة دجاج",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "60,000", USD: "", TRY: "" },
      },
      {
        name: "كبسة دجاج",
        desc: "2 فخد",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "100,000", USD: "", TRY: "" },
      },
      {
        name: "منسف دفين",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "120,000", USD: "", TRY: "" },
      },
      {
        name: "كباب هندي",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "صفيحة شاميّة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "صفيحة فطاير",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "صفيحة خضار سواريه",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "400,000", USD: "", TRY: "" },
      },
      {
        name: "صفيحة شاميّة باللبن",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "صينيّة لحمة ناعمة بالخضار",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "صينيّة لحمة ناعمة بالطحينية",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "صينيّة شرحات سادة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "470,000", USD: "", TRY: "" },
      },
      {
        name: "صينيّة شرحات بالطحينية",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "470,000", USD: "", TRY: "" },
      },
      {
        name: "صينيّة شرحات مطفاية",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "470,000", USD: "", TRY: "" },
      },
      {
        name: "شرحات لحمة بعجين",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "470,000", USD: "", TRY: "" },
      },
      {
        name: "شرحات عجين سواريه",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "470,000", USD: "", TRY: "" },
      },
      {
        name: "صينيّة لحمة مجرمشة بالخضار",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "430,000", USD: "", TRY: "" },
      },
      {
        name: "لحمة مجرمشة عجين بالخضار",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "430,000", USD: "", TRY: "" },
      },
      {
        name: "لحمة مجرمشة عجين سادة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "430,000", USD: "", TRY: "" },
      },
      {
        name: "لحمة مجرمشة عجين سواريه بالخضار",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "440,000", USD: "", TRY: "" },
      },
      {
        name: "لحمة مجرمشة عجين سواريه سادة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "440,000", USD: "", TRY: "" },
      },
      {
        name: "شرحات دجاج عجين سواريه",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "180,000", USD: "", TRY: "" },
      },
      {
        name: "ليّة على عجين",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "250,000", USD: "", TRY: "" },
      },
      {
        name: "بيضات خاروف بالعجيبن",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "350,000", USD: "", TRY: "" },
      },
      {
        name: "بيضات خاروف عجين سواريه",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "360,000", USD: "", TRY: "" },
      },
      {
        name: "بيضات خاروف بالصينيّة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "350,000", USD: "", TRY: "" },
      },
      {
        name: "سناسل بالعجين",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "350,000", USD: "", TRY: "" },
      },
      {
        name: "صينيّة سناسل",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "350,000", USD: "", TRY: "" },
      },
      {
        name: "سودة بالصينيّة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "250,000", USD: "", TRY: "" },
      },
      {
        name: "سودة بالعجين",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "250,000", USD: "", TRY: "" },
      },
      {
        name: "ماريّا عرايس",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "طوشكا",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "55,000", USD: "", TRY: "" },
      },
      {
        name: "فخّارة لحمة وخاضر",
        desc: "كبيرة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "650,000", USD: "", TRY: "" },
      },
      {
        name: "فخّارة دجاج وقشقوان",
        desc: "كبيرة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "360,000", USD: "", TRY: "" },
      },
      {
        name: "وجبة رز سادة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
      {
        name: "زر أبيض سادة",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "western",
    title: "المأكولات الغربية",
    icon: "🍝",
    items: [
      {
        name: "كوردن بلو",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "85,000", USD: "", TRY: "" },
      },
      {
        name: "كريسبي",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "كرانشي",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "اسكالوب",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "فاهيتا",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "زنجر",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "سندوتش غربي",
        desc: "كريسبي, كرانشي, اسكالوب, فاهيتا, زنجر",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "شاورما دجاج",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "60,000", USD: "", TRY: "" },
      },
      {
        name: "شاورما لحمة",
        desc:  "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
      {
        name: "بطاطا تركية",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "بطاطا تركية شيدر",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "55,000", USD: "", TRY: "" },
      },
      {
        name: "سندوتش شاورما دجاج",
        desc: "عدد 1",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "سندوتش شاورما لحمة",
        desc: "عدد 1",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "سندوتش بطاطا",
        desc: "عدد 1",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "10,000", USD: "", TRY: "" },
      },
      {
        name: "شاورما إيطالية بالفرن دجاج",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "70,000", USD: "", TRY: "" },
      },
      {
        name: "شاورما إيطالية بالفرن لحمة",
        desc: "وجبة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "100,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "grills",
    title: "المشاوي",
    icon: "🍢",
    items: [
      {
        name: "جاط مشاوي مشكل",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "ريش لحمة مشويّة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "شقف لحمة خاروف",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "470,000", USD: "", TRY: "" },
      },
      {
        name: "كباب لحمة خاروف",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "فتايل لحمة وليّة مشويّة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "420,000", USD: "", TRY: "" },
      },
      {
        name: "ليّة مشويّة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "250,000", USD: "", TRY: "" },
      },
      {
        name: "شيش طاووق",
        desc: "كيلو",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "180,000", USD: "", TRY: "" },
      },
      {
        name: "جناح دجاج مشويّة",
        desc: "كيلو غرام",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "130,000", USD: "", TRY: "" },
      },
      {
        name: "فخد دجاج",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "كبّة على السيخ",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "390,000", USD: "", TRY: "" },
      },
      {
        name: "كبّة مشويّة",
        desc: "القطعة الواحدة",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "pastries",
    title: "المعجنات",
    icon: "🥐",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "70,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "7,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "7,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "5,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "2,500", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "5,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "5,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "7,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "5,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "16,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "9,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "7,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "20,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "20,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "30,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "4,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "sweets",
    title: "الحلويات",
    icon: "🍰",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "60,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "150,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "55,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "55,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "40,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "150,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "30,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "30,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "125,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "150,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "90,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "110,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "70,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "90,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "90,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "110,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "80,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "icecream",
    title: "البوظة",
    icon: "🍨",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "75,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "85,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "5,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "fruits",
    title: "الفواكه",
    icon: "🍓",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "60,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "60,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "25,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "35,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "85,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "nuts",
    title: "المكسرات",
    icon: "🥜",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "20,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "55,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "12,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "42,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "46,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "55,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "75,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "50,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "45,000", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "juices",
    title: "عصائر طبيعية",
    icon: "🧃",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "27,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "27,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "27,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "27,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "27,000", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "cold",
    title: "المشروبات الباردة",
    icon: "🥤",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "hot",
    title: "المشروبات الساخنة",
    icon: "☕",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
    ],
  },
  {
    id: "shisha",
    title: "الأراجيل",
    icon: "💨",
    items: [
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
      {
        name: "",
        desc: "",
        image: "/menu/placeholder.jpg",
        prices: { SYP: "", USD: "", TRY: "" },
      },
    ],
  },
];
export const galleryItems = [
  {
    title: "الواجهة",
    text: "واجهة المكان وموقعه المميز على أوتستراد دمشق مقابل مدخل مدينة النبك.",
    image: "/images/front.jpg",
  },
  {
    title: "قسم المطعم",
    text: "جلسات مريحة وتجربة طعام مميزة ضمن الطابق الأول.",
    image: "/images/restaurant.jpg",
  },
  {
    title: "الكافيه والتراس",
    text: "أجواء هادئة وجلسات راقية في الطابق الثاني.",
    image: "/images/cafe-terrace.jpg",
  },
  {
    title: "صالة الأفراح",
    text: "مساحة مخصصة للمناسبات الخاصة في الطابق الثالث.",
    image: "/images/events-hall.jpg",
  },
  {
    title: "قسم الحلويات",
    text: "ركن خاص للحلويات يكمل تجربة الضيافة بنكهات مميزة.",
    image: "/images/sweets.jpg",
  },
  {
    title: "ألعاب الأطفال",
    text: "مساحة مخصصة للأطفال لتجربة عائلية أكثر راحة ومتعة.",
    image: "/images/kids-area.jpg",
  },
];
