export const siteConfig = {
  name: "مطعم واستراحة ابن النبك",
  shortName: "ابن النبك",
  slogan: "وجهتكم المتكاملة في النبك",
  description:
    "مطعم، كافيه وتراس، صالة أفراح، حلويات، وألعاب أطفال في مكان واحد",
  address: "أوتستراد دمشق، مقابل مدخل مدينة النبك",
  heroImage: "/images/hero.jpg",

  logoSrc: "/branding/logo.png",
  logoAlt: "شعار مطعم واستراحة ابن النبك",

  // ===== بيانات مؤقتة - يتم تحديثها لاحقاً =====
  phoneDisplay: "+963 000 000 000",
  phoneHref: "tel:+963000000000",
  whatsappNumber: "963000000000",
mapsHref: "https://maps.app.goo.gl/ReDofToXDJXsmmVx6",
mapsEmbed:
  "https://www.google.com/maps?q=34.0286,36.7236&hl=ar&z=17&output=embed",
  // ===== السوشال ميديا (اختياري) =====
  social: {
    facebook: "",
    instagram: "",
    tiktok: "",
  },
};

export const whatsappMessage = encodeURIComponent(
  "مرحبًا، أرغب بالطلب أو الاستفسار من مطعم واستراحة ابن النبك"
);

export const whatsappHref = `https://wa.me/${siteConfig.whatsappNumber}?text=${whatsappMessage}`;

export const navLinks = [
  { label: "الرئيسية", href: "#top" },
  { label: "أقسامنا", href: "#sections" },
  { label: "المعرض", href: "#gallery" },
  { label: "المنيو", href: "/menu" },
  { label: "صالة الأفراح", href: "#events" },
  { label: "تواصل معنا", href: "#contact" },
];

export const stats = [
  { value: "3", label: "طوابق رئيسية" },
  { value: "عائلي", label: "مناسب للعائلات" },
  { value: "صيفي", label: "تراس خارجي موسمي" },
];

export const venueSections = [
  {
    title: "الطابق الأول",
    subtitle: "المطعم + الحلويات + ألعاب الأطفال",
    description:
      "يضم قسم المطعم الرئيسي، وقسمًا خاصًا بالحلويات، بالإضافة إلى مساحة مخصصة لألعاب الأطفال لتجربة عائلية متكاملة.",
    items: ["قسم المطعم", "قسم الحلويات", "ألعاب الأطفال"],
  },
  {
    title: "الطابق الثاني",
    subtitle: "الكافيه + التراس",
    description:
      "جلسات مريحة وأجواء راقية تناسب اللقاءات العائلية والجلسات المسائية، مع مساحة تراس مميزة.",
    items: ["قسم الكافيه", "التراس", "جلسات مريحة"],
  },
  {
    title: "الطابق الثالث",
    subtitle: "صالة الأفراح",
    description:
      "صالة مخصصة لاستقبال المناسبات الخاصة والأفراح في أجواء أنيقة وخدمة مميزة.",
    items: ["صالة أفراح", "مناسبات خاصة", "استفسار عبر الهاتف"],
  },
  {
    title: "المساحة الخارجية",
    subtitle: "تراس صيفي أمام الاستراحة",
    description:
      "في فصل الصيف، تتوفر جلسات خارجية مميزة أمام الاستراحة لتجربة أكثر انتعاشًا وراحة.",
    items: ["تراس خارجي", "جلسات صيفية", "واجهة مريحة"],
  },
];

export const highlights = [
  {
    title: "قسم الحلويات",
    text: "ركن خاص للحلويات يضيف لمسة ضيافة راقية ويكمل تجربة الزوار بنكهات مميزة.",
  },
  {
    title: "ألعاب الأطفال",
    text: "مساحة مخصصة للأطفال تمنح العائلة راحة أكبر أثناء الجلسة داخل المطعم والاستراحة.",
  },
  {
    title: "الكافيه والتراس",
    text: "جلسات هادئة وتصميم مريح يناسب اللقاءات اليومية والجلسات المسائية مع الأصدقاء والعائلة.",
  },
  {
    title: "صالة الأفراح",
    text: "خيار مثالي للمناسبات الخاصة ضمن مكان واحد يجمع بين الضيافة والأجواء الأنيقة.",
  },
];

// ===== العملات المتاحة =====
export const currencies = [
  { code: "SYP", label: "ل.س", name: "ليرة سورية" },
  { code: "USD", label: "$", name: "دولار" },
  { code: "TRY", label: "₺", name: "ليرة تركية" },
];

// ===== أقسام المنيو =====
export const menuCategories = [
  {
    id: "breakfast",
    title: "الإفطار",
    icon: "🍳",
    items: [
      { name: "صحن زيتون", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "صحن لبنة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "صحن جبنة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "صحن خضرة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "حمّص باللحمة", desc: "100 غرام", image: "/menu/placeholder.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "فول بالزيت", desc: "للشخص الواحد", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "فول بلبن", desc: "للشخص الواحد", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "حمّص بالزيت", desc: "للشخص الواحد", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "حمّص باللبن", desc: "للشخص الواحد", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "فتة بالزيت", desc: "للشخص الواحد", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "فتة بالسمنة", desc: "للشخص الواحد", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "زعتر ابن النبك", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "زعتر و قشوان", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "بيضة مقلية", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "4,000", USD: "0.28", TRY: "13.3" } },
      { name: "خبز تميس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "10,000", USD: "0.70", TRY: "33.3" } },
      { name: "خبز تميس بالجبنة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "خبز تميس دبل جبنة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "صحن قشطة عربية", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
    ],
  },
  {
    id: "appetizers",
    title: "المقبلات",
    icon: "🥗",
    items: [
      { name: "حمص باللحمة", desc: "100 g", image: "/menu/placeholder.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "حمص باللحمة", desc: "200 g", image: "/menu/placeholder.jpg", prices: { SYP: "120,000", USD: "8.5", TRY: "400" } },
      { name: "مسبحة باللية", desc: "100 g", image: "/menu/appetizers/musabaha-liyyeh.jpg", prices: { SYP: "65,000", USD: "4.6", TRY: "216.7" } },
      { name: "صحن مقبلات مشكل", desc: "", image: "/menu/appetizers/mezza-mix.jpg", prices: { SYP: "95,000", USD: "6.7", TRY: "316.7" } },
      { name: "مسبحة", desc: "", image: "/menu/appetizers/musabaha.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "متبل", desc: "", image: "/menu/appetizers/mutabbal.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "بابا غنوج", desc: "", image: "/menu/appetizers/baba-ghanouj.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "حمص بيروتي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "متبل شوندر", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "محمرة", desc: "", image: "/menu/appetizers/muhammara.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "شنكليش", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "كبة نية", desc: "", image: "/menu/appetizers/kibbeh-nayyeh.jpg", prices: { SYP: "90,000", USD: "6.3", TRY: "300" } },
      { name: "هبرة نية", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "90,000", USD: "6.3", TRY: "300" } },
      { name: "جاط خضرة اكسترا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "250,000", USD: "17.6", TRY: "833.3" } },
      { name: "بطاطا مقلية", desc: "", image: "/menu/appetizers/fries.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "برك جبنة", desc: "القطعة الواحدة", image: "/menu/appetizers/burek-cheese.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "زبدية لبن", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
      { name: "صحن مايونيز", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "10,000", USD: "0.70", TRY: "33.3" } },
    ],
  },
  {
    id: "salads",
    title: "السلطات",
    icon: "🥬",
    items: [
      { name: "تبولة", desc: "", image: "/menu/salads/tabbouleh.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "فتّوش", desc: "", image: "/menu/salads/fattoush.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "سلطة شرقيّة", desc: "", image: "/menu/salads/salad-eastern.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "سلطة أرمينية", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "سلطة سيزر", desc: "", image: "/menu/salads/salad-caesar.jpg", prices: { SYP: "65,000", USD: "4.6", TRY: "216.7" } },
      { name: "سلطة سويسرية", desc: "", image: "/menu/salads/salad-swiss.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "سلطة جرجير", desc: "", image: "/menu/salads/salad-rocca.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "سلطة شوندر", desc: "", image: "/menu/salads/salad-beetroot.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
    ],
  },
  {
    id: "eastern",
    title: "المأكولات الشرقية",
    icon: "🍛",
    items: [
      { name: "فريكة لحمة", desc: "", image: "/menu/eastern/freekeh-meat.jpg", prices: { SYP: "120,000", USD: "8.5", TRY: "400" } },
      { name: "فريكة دجاج", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "60,000", USD: "4.2", TRY: "200" } },
      { name: "كبسة لحمة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "120,000", USD: "8.5", TRY: "400" } },
      { name: "كبسة دجاج", desc: "", image: "/menu/eastern/kabsa-chicken.jpg", prices: { SYP: "60,000", USD: "4.2", TRY: "200" } },
      { name: "كبسة دجاج", desc: "2 فخد", image: "/menu/eastern/kabsa-chicken.jpg", prices: { SYP: "100,000", USD: "7", TRY: "333.3" } },
      { name: "منسف دفين", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "120,000", USD: "8.5", TRY: "400" } },
      { name: "كباب هندي", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "صفيحة شاميّة", desc: "كيلو غرام", image: "/menu/eastern/safiha-shamiyya.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "صفيحة فطاير", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "صفيحة خضار سواريه", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "400,000", USD: "28.2", TRY: "1,333.3" } },
      { name: "صفيحة شاميّة باللبن", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "صينيّة لحمة ناعمة بالخضار", desc: "كيلو غرام", image: "/menu/eastern/meat-soft-vegetables.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "صينيّة لحمة ناعمة بالطحينية", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "صينيّة شرحات سادة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "470,000", USD: "33.1", TRY: "1,566.7" } },
      { name: "صينيّة شرحات بالطحينية", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "470,000", USD: "33.1", TRY: "1,566.7" } },
      { name: "صينيّة شرحات مطفاية", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "470,000", USD: "33.1", TRY: "1,566.7" } },
      { name: "شرحات لحمة بعجين", desc: "كيلو غرام", image: "/menu/eastern/shrhat-dough.jpg", prices: { SYP: "470,000", USD: "33.1", TRY: "1,566.7" } },
      { name: "شرحات عجين سواريه", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "470,000", USD: "33.1", TRY: "1,566.7" } },
      { name: "صينيّة لحمة مجرمشة بالخضار", desc: "كيلو غرام", image: "/menu/eastern/meat-crispy-vegetables.jpg", prices: { SYP: "430,000", USD: "30.3", TRY: "1,433.3" } },
      { name: "لحمة مجرمشة عجين بالخضار", desc: "كيلو غرام", image: "/menu/eastern/meat-crispy-dough-veg.jpg", prices: { SYP: "430,000", USD: "30.3", TRY: "1,433.3" } },
      { name: "لحمة مجرمشة عجين سادة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "430,000", USD: "30.3", TRY: "1,433.3" } },
      { name: "لحمة مجرمشة عجين سواريه بالخضار", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "440,000", USD: "31", TRY: "1,466.7" } },
      { name: "لحمة مجرمشة عجين سواريه سادة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "440,000", USD: "31", TRY: "1,466.7" } },
      { name: "شرحات دجاج عجين سواريه", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "180,000", USD: "12.7", TRY: "600" } },
      { name: "ليّة على عجين", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "250,000", USD: "17.6", TRY: "833.3" } },
      { name: "بيضات خاروف بالعجين", desc: "كيلو غرام", image: "/menu/eastern/lamb-eggs-dough.jpg", prices: { SYP: "350,000", USD: "24.6", TRY: "1,166.7" } },
      { name: "بيضات خاروف عجين سواريه", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "360,000", USD: "25.4", TRY: "1,200" } },
      { name: "بيضات خاروف بالصينيّة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "350,000", USD: "24.6", TRY: "1,166.7" } },
      { name: "سناسل بالعجين", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "350,000", USD: "24.6", TRY: "1,166.7" } },
      { name: "صينيّة سناسل", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "350,000", USD: "24.6", TRY: "1,166.7" } },
      { name: "سودة بالصينيّة", desc: "كيلو غرام", image: "/menu/eastern/liver-tray.jpg", prices: { SYP: "250,000", USD: "17.6", TRY: "833.3" } },
      { name: "سودة بالعجين", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "250,000", USD: "17.6", TRY: "833.3" } },
      { name: "ماريّا عرايس", desc: "كيلو غرام", image: "/menu/eastern/mariya-arayes.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "طوشكا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "55,000", USD: "3.9", TRY: "183.3" } },
      { name: "فخّارة لحمة وخاضر", desc: "كبيرة", image: "/menu/placeholder.jpg", prices: { SYP: "650,000", USD: "45.8", TRY: "2,166.7" } },
      { name: "فخّارة دجاج وقشقوان", desc: "كبيرة", image: "/menu/placeholder.jpg", prices: { SYP: "360,000", USD: "25.4", TRY: "1,200" } },
      { name: "وجبة رز سادة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "زر أبيض سادة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
    ],
  },
  {
    id: "western",
    title: "المأكولات الغربية",
    icon: "🍝",
    items: [
      { name: "كوردن بلو", desc: "وجبة", image: "/menu/western/cordon-bleu.jpg", prices: { SYP: "85,000", USD: "6", TRY: "283.3" } },
      { name: "كريسبي", desc: "وجبة", image: "/menu/western/crispy.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "كرانشي", desc: "وجبة", image: "/menu/western/crunchy.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "اسكالوب", desc: "وجبة", image: "/menu/western/escalope.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "فاهيتا", desc: "وجبة", image: "/menu/placeholder.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "زنجر", desc: "وجبة", image: "/menu/placeholder.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "سندوتش غربي", desc: "كريسبي, كرانشي, اسكالوب, فاهيتا, زنجر", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "شاورما دجاج", desc: "وجبة", image: "/menu/western/shawarma-chicken-meal.jpg", prices: { SYP: "60,000", USD: "4.2", TRY: "200" } },
      { name: "شاورما لحمة", desc: "وجبة", image: "/menu/placeholder.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
      { name: "بطاطا تركية", desc: "وجبة", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "بطاطا تركية شيدر", desc: "وجبة", image: "/menu/placeholder.jpg", prices: { SYP: "55,000", USD: "3.9", TRY: "183.3" } },
      { name: "سندوتش شاورما دجاج", desc: "عدد 1", image: "/menu/western/shawarma-chicken-sandwich.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "سندوتش شاورما لحمة", desc: "عدد 1", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "سندوتش بطاطا", desc: "عدد 1", image: "/menu/placeholder.jpg", prices: { SYP: "10,000", USD: "0.70", TRY: "33.3" } },
      { name: "شاورما إيطالية بالفرن دجاج", desc: "وجبة", image: "/menu/placeholder.jpg", prices: { SYP: "70,000", USD: "4.9", TRY: "233.3" } },
      { name: "شاورما إيطالية بالفرن لحمة", desc: "وجبة", image: "/menu/placeholder.jpg", prices: { SYP: "100,000", USD: "7", TRY: "333.3" } },
    ],
  },
  {
    id: "grills",
    title: "المشاوي",
    icon: "🍢",
    items: [
      { name: "جاط مشاوي مشكل", desc: "كيلو غرام", image: "/menu/grills/mixed-grill.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "ريش لحمة مشويّة", desc: "كيلو غرام", image: "/menu/grills/lamb-ribs.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "شقف لحمة خاروف", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "470,000", USD: "33.1", TRY: "1,566.7" } },
      { name: "كباب لحمة خاروف", desc: "كيلو غرام", image: "/menu/grills/lamb-kebab.webp", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "فتايل لحمة وليّة مشويّة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "420,000", USD: "29.6", TRY: "1,400" } },
      { name: "ليّة مشويّة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "250,000", USD: "17.6", TRY: "833.3" } },
      { name: "شيش طاووق", desc: "كيلو", image: "/menu/grills/shish-tawook.jpg", prices: { SYP: "180,000", USD: "12.7", TRY: "600" } },
      { name: "جناح دجاج مشويّة", desc: "كيلو غرام", image: "/menu/grills/chicken-wings.jpg", prices: { SYP: "130,000", USD: "9.2", TRY: "433.3" } },
      { name: "فخد دجاج", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "كبّة على السيخ", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "390,000", USD: "27.5", TRY: "1,300" } },
      { name: "كبّة مشويّة", desc: "القطعة الواحدة", image: "/menu/grills/kibbeh-grilled.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
    ],
  },
  {
    id: "pastries",
    title: "المعجنات",
    icon: "🥐",
    items: [
      { name: "بيتزا ابن النبك", desc: "", image: "/menu/pastries/pizza-special.jpg", prices: { SYP: "70,000", USD: "4.9", TRY: "233.3" } },
      { name: "بيتزا خضار", desc: "", image: "/menu/pastries/pizza-vegetables.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "بيتزا مرغريتا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "محمرة قشقوان", desc: "", image: "/menu/pastries/muhammara-cheese.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "زعتر قشقوان", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "فطاير جبنة", desc: "القطعة الواحدة", image: "/menu/pastries/fatayer-cheese.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
      { name: "خبز مشروح", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "2,500", USD: "0.18", TRY: "8.3" } },
      { name: "زعتر", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
      { name: "محمرة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
      { name: "قشقوان مع زيتون", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "مخلوطة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
      { name: "دجاج وقشقوان", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "16,000", USD: "1.1", TRY: "53.3" } },
      { name: "مرتديلا بقشقوان", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "9,000", USD: "0.63", TRY: "30" } },
      { name: "قشقوان", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "شختورة جبنة تركية", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "فطيرة تركية جبنة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "بيتزا صغيرة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "سواريه مشكل", desc: "القطعة الواحدة", image: "/menu/pastries/soiree-mix.jpg", prices: { SYP: "4,000", USD: "0.28", TRY: "13.3" } },
    ],
  },
  {
    id: "sweets",
    title: "الحلويات",
    icon: "🍰",
    items: [
      { name: "كريب فواكه", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "كريب شوكولا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "كريب قشطة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "60,000", USD: "4.2", TRY: "200" } },
      { name: "كريب فوتوتشيني", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "كريب كيك", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "كريب لوتس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "كريب عيد ميلاد", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "150,000", USD: "10.6", TRY: "500" } },
      { name: "كيكة غوفر", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "55,000", USD: "3.9", TRY: "183.3" } },
      { name: "كيكة دونيستا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "55,000", USD: "3.9", TRY: "183.3" } },
      { name: "بان كيك فواكه", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "بان كيك شوكولا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "بان كيك لوتس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "بان كيك عيد ميلاد", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "150,000", USD: "10.6", TRY: "500" } },
      { name: "تشيز كيك لوتس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "تشيز كيك شوكولا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "تشيز كيك فريز", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "تشيز كيك عيد ميلاد", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "125,000", USD: "8.8", TRY: "416.7" } },
      { name: "عرباية فواكه بالقشطة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "150,000", USD: "10.6", TRY: "500" } },
      { name: "هريسة بالفستق الحلبي", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "90,000", USD: "6.3", TRY: "300" } },
      { name: "هريسة بالقشطة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "110,000", USD: "7.7", TRY: "366.7" } },
      { name: "هريسة اكسترا", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "70,000", USD: "4.9", TRY: "233.3" } },
      { name: "هريسة اكسترا بالقشطة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "90,000", USD: "6.3", TRY: "300" } },
      { name: "هريسة بالفستق المبشور", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "هريسة سوبر اكسترا", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "90,000", USD: "6.3", TRY: "300" } },
      { name: "هريسة سوبر اكسترا بالقشطة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "110,000", USD: "7.7", TRY: "366.7" } },
      { name: "حلاوة جبن بالقشطة", desc: "كيلو غرام", image: "/menu/placeholder.jpg", prices: { SYP: "80,000", USD: "5.6", TRY: "266.7" } },
    ],
  },
  {
    id: "icecream",
    title: "البوظة",
    icon: "🍨",
    items: [
      { name: "بوظة بغزل البنات", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "بوظة عربي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "شوكلامو", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "75,000", USD: "5.3", TRY: "250" } },
      { name: "شوكلامو سبيشل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "85,000", USD: "6", TRY: "283.3" } },
      { name: "كرانشي ايس كريم", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "سكوب بوظة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
    ],
  },
  {
    id: "fruits",
    title: "الفواكه",
    icon: "🍓",
    items: [
      { name: "سلطة ارمادا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "60,000", USD: "4.2", TRY: "200" } },
      { name: "سلطة فواكه", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "سلطة فواكه نوتيلا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "60,000", USD: "4.2", TRY: "200" } },
      { name: "فواكه وبطيخ وخدمة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "صحن بطيخ تنزيل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "قشاطي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "85,000", USD: "6", TRY: "283.3" } },
    ],
  },
  {
    id: "nuts",
    title: "المكسرات",
    icon: "🥜",
    items: [
      { name: "فستق مدخن بلدي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "مكاديميا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "55,000", USD: "3.9", TRY: "183.3" } },
      { name: "لوز مشكل", desc: "500 غرام", image: "/menu/placeholder.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "بوشار", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "12,000", USD: "0.85", TRY: "40" } },
      { name: "كعك سادة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "42,000", USD: "3", TRY: "140" } },
      { name: "كعك سمسم", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "46,000", USD: "3.2", TRY: "153.3" } },
      { name: "كيس مكسرات اكسترا احمر", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "55,000", USD: "3.9", TRY: "183.3" } },
      { name: "كيس مكسرات اكسترا ازرق", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "75,000", USD: "5.3", TRY: "250" } },
      { name: "كيس مكسرات فانيتي نهدي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "مشكل لوز", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
    ],
  },
  {
    id: "juices",
    title: "عصائر طبيعية",
    icon: "🧃",
    items: [
      { name: "توت", desc: "", image: "/menu/juices/juice-berry.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "توت وفريز", desc: "", image: "/menu/juices/juice-berry-strawberry.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "فريز", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "فريز وبطيخ وليمون", desc: "", image: "/menu/juices/juice-strawberry-watermelon.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "برتقال", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "برتقال وفريز", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "تفاح", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "ليموناده", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "23,000", USD: "1.6", TRY: "76.7" } },
      { name: "ليموناده بالزنجبيل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "ليمون", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "23,000", USD: "1.6", TRY: "76.7" } },
      { name: "بولو", desc: "", image: "/menu/juices/juice-polo.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "بولو بالزنجبيل", desc: "", image: "/menu/juices/juice-polo.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "رمان", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "بطيخ", desc: "", image: "/menu/juices/juice-watermelon.jpg", prices: { SYP: "23,000", USD: "1.6", TRY: "76.7" } },
      { name: "كيوي واناناس وليمون", desc: "", image: "/menu/juices/juice-kiwi-pineapple.jpg", prices: { SYP: "34,000", USD: "2.4", TRY: "113.3" } },
      { name: "اناناس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "27,000", USD: "1.9", TRY: "90" } },
      { name: "اناناس بجوز الهند", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "اناناس وفريز", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "34,000", USD: "2.4", TRY: "113.3" } },
      { name: "منغا", desc: "", image: "/menu/juices/juice-mango.jpg", prices: { SYP: "33,000", USD: "2.3", TRY: "110" } },
    ],
  },
  {
    id: "cold",
    title: "المشروبات الباردة",
    icon: "🥤",
    items: [
      { name: "امبراطور", desc: "", image: "/menu/cold/emperor.jpg", prices: { SYP: "85,000", USD: "6", TRY: "283.3" } },
      { name: "ميلك شيك لوتس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "ميلك شيك اوريو", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "ميلك شيك فانيلا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "ميلك شيك شوكولا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "ميلك شيك فريز", desc: "", image: "/menu/cold/milkshake-strawberry.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "ميلك شيك على كيفك", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "كوكتيل منغا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "كوكتيل اناناس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "33,000", USD: "2.3", TRY: "110" } },
      { name: "كوكتيل موز وحليب", desc: "", image: "/menu/cold/cocktail-banana-milk.jpg", prices: { SYP: "33,000", USD: "2.3", TRY: "110" } },
      { name: "كوكتيل موز وحليب وفريز", desc: "", image: "/menu/cold/cocktail-banana-strawberry.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "كوكتيل موز وحليب وشوكولا", desc: "", image: "/menu/cold/cocktail-banana-chocolate.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "كوكتيل افوكادو", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "50,000", USD: "3.5", TRY: "166.7" } },
      { name: "فخفخينا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "موهيتو", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "موهيتو ريد بول", desc: "", image: "/menu/cold/mojito-redbull.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "موهيتو سفن", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "ايس كوفي", desc: "", image: "/menu/cold/ice-coffee.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "ايس موكا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "ايس كريم كراميل", desc: "", image: "/menu/cold/ice-caramel.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "ميكس اناناس", desc: "", image: "/menu/cold/mix-pineapple.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "غراندين", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "24,000", USD: "1.7", TRY: "80" } },
      { name: "جلاب", desc: "1 لتر", image: "/menu/placeholder.jpg", prices: { SYP: "15,000", USD: "1.1", TRY: "50" } },
      { name: "سفن اب اكسترا", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "سلس", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "6,000", USD: "0.42", TRY: "20" } },
      { name: "لبن عيران صغير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "6,000", USD: "0.42", TRY: "20" } },
      { name: "لبن عيران كبير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "مشروبات غازية", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "10,000", USD: "0.70", TRY: "33.3" } },
      { name: "مياه", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
    ],
  },
  {
    id: "hot",
    title: "المشروبات الساخنة",
    icon: "☕",
    items: [
      { name: "كاسة كرك", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "15,000", USD: "1.1", TRY: "50" } },
      { name: "اسبريسو دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "15,000", USD: "1.1", TRY: "50" } },
      { name: "اسبريسو عادي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "8,000", USD: "0.56", TRY: "26.7" } },
      { name: "اسبريسو مع نسلة دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "18,000", USD: "1.3", TRY: "60" } },
      { name: "اسبريسو مع نسلة عادي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "12,000", USD: "0.85", TRY: "40" } },
      { name: "قهوة تركية دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "14,000", USD: "1", TRY: "46.7" } },
      { name: "قهوة تركية عادي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كابتشينو دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "كابتشينو عادي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "12,000", USD: "0.85", TRY: "40" } },
      { name: "هوت شوكوليت دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "هوت شوكوليت عادي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "14,000", USD: "1", TRY: "46.7" } },
      { name: "نسكافيه 3 ب 1 دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "نسكافيه 3 ب 1 عادي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "14,000", USD: "1", TRY: "46.7" } },
      { name: "نسكافيه بلاك دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "25,000", USD: "1.8", TRY: "83.3" } },
      { name: "نسكافيه بلاك عادي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "16,000", USD: "1.1", TRY: "53.3" } },
      { name: "سحلب", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "15,000", USD: "1.1", TRY: "50" } },
      { name: "ميلو بحليب", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "16,000", USD: "1.1", TRY: "53.3" } },
      { name: "كاسة بابونج", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة زنجبيل وليمون", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة زهورات", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة قرفة وزنجبيل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة كمون وليمون", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة مليسة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة شاي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
      { name: "كاسة شاي أخضر", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة شاي بالقرفة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "كاسة شاي بالليمون والنعنع", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "7,000", USD: "0.49", TRY: "23.3" } },
      { name: "ابريق بابونج صغير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "15,000", USD: "1.1", TRY: "50" } },
      { name: "ابريق بابونج كبير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "ابريق شاي صغير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "15,000", USD: "1.1", TRY: "50" } },
      { name: "ابريق شاي كبير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "ابريق شاي كرك صغير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "30,000", USD: "2.1", TRY: "100" } },
      { name: "ابريق شاي كرك كبير", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "47,000", USD: "3.3", TRY: "156.7" } },
    ],
  },
  {
    id: "shisha",
    title: "الأراجيل",
    icon: "💨",
    items: [
      { name: "اركيلة راس دبل نخلة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "45,000", USD: "3.2", TRY: "150" } },
      { name: "أركيلة تفاحتين نخلة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "اركيلة تفاحتين فاخر", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة ميكس تفاحتين", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة راس دبل", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "40,000", USD: "2.8", TRY: "133.3" } },
      { name: "أركيلة بلو بيري", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة بولو", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة عنب", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة عنب ونعنع", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة لوف", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة مسكة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة مسكة وقرفة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "اركيلة مسكة ونعناع", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "35,000", USD: "2.5", TRY: "116.7" } },
      { name: "بربيش صحي", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "5,000", USD: "0.35", TRY: "16.7" } },
      { name: "خدمة أركيلة", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
      { name: "خدمة فحم", desc: "", image: "/menu/placeholder.jpg", prices: { SYP: "20,000", USD: "1.4", TRY: "66.7" } },
    ],
  },
];
export const galleryItems = [
  {
    title: "الواجهة",
    text: "واجهة المكان وموقعه المميز على أوتستراد دمشق مقابل مدخل مدينة النبك.",
    image: "/images/front.jpg",
  },
  {
    title: "قسم المطعم",
    text: "جلسات مريحة وتجربة طعام مميزة ضمن الطابق الأول.",
    image: "/images/restaurant.jpg",
  },
  {
    title: "الكافيه والتراس",
    text: "أجواء هادئة وجلسات راقية في الطابق الثاني.",
    image: "/images/cafe-terrace.jpg",
  },
  {
    title: "صالة الأفراح",
    text: "مساحة مخصصة للمناسبات الخاصة في الطابق الثالث.",
    image: "/images/events-hall.jpg",
  },
  {
    title: "قسم الحلويات",
    text: "ركن خاص للحلويات يكمل تجربة الضيافة بنكهات مميزة.",
    image: "/images/sweets.jpg",
  },
  {
    title: "ألعاب الأطفال",
    text: "مساحة مخصصة للأطفال لتجربة عائلية أكثر راحة ومتعة.",
    image: "/images/kids-area.jpg",
  },
];
